# Generated by Django 5.1.5 on 2025-04-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
    ]
