# Generated by Django 5.1.4 on 2025-01-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="zipcpde",
            new_name="zipcode",
        ),
    ]
